spring:
    application:
        name: pizzamania
    datasource:
        generate-unique-name: false
        name: pizzamania
    sql:
        init:
            encoding: UTF-8
server:
    servlet:
        encoding:
            charset: UTF-8