delete from Ingredient_Ref;
delete from Pizza;
delete from Pizza_Order;
delete from Ingredient;

insert into Ingredient (id, name, type) values ('QUMO', 'Queso Mozzarella', 'QUESO');
insert into Ingredient (id, name, type) values ('QUPR', 'Queso Provolone', 'QUESO');
insert into Ingredient (id, name, type) values ('QUPA', 'Queso Parmesano', 'QUESO');
insert into Ingredient (id, name, type) values ('QURO', 'Queso Roquefort', 'QUESO');
insert into Ingredient (id, name, type) values ('QUCA', 'Queso de cabra', 'QUESO');
insert into Ingredient (id, name, type) values ('PRPO', 'Pollo', 'PROTEINA');
insert into Ingredient (id, name, type) values ('PRPA', 'Panceta', 'PROTEINA');
insert into Ingredient (id, name, type) values ('PRAN', 'Anchoas', 'PROTEINA');
insert into Ingredient (id, name, type) values ('PRCP', 'Carne picada', 'PROTEINA');
insert into Ingredient (id, name, type) values ('PRHU', 'Huevo', 'PROTEINA');
insert into Ingredient (id, name, type) values ('VECE', 'Cebolla', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VETP', 'Tomate perita', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VETC', 'Tomate cherry', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VERU', 'Rúcula', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VEES', 'Espinaca', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VEBE', 'Berenjena', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VEZU', 'Zucchini', 'VEGETAL');
insert into Ingredient (id, name, type) values ('VECH', 'Choclo', 'VEGETAL');
insert into Ingredient (id, name, type) values ('FRAN', 'Ananá', 'FRUTA');
insert into Ingredient (id, name, type) values ('FRMA', 'Manzana', 'FRUTA');
insert into Ingredient (id, name, type) values ('EXOR', 'Orégano', 'EXTRA');
insert into Ingredient (id, name, type) values ('EXAJ', 'Ají molido', 'EXTRA');
insert into Ingredient (id, name, type) values ('EXAO', 'Aceite de oliva', 'EXTRA');
insert into Ingredient (id, name, type) values ('EXMI', 'Miel', 'EXTRA');
insert into Ingredient (id, name, type) values ('EXNU', 'Nueces', 'EXTRA');